export const fieldCourses = [
  {
    id: "1",
    nameCourse: "Môn học 1",
    descriptionCourse: "Môn học 1",
    tutors: [
      {
        id: "1",
        name: "Tutor 1",
        avatar: "/assets/avatar-tutor-2.png",
        age: 22,
        yoe: 2,
        gender: "Male",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
      {
        id: "2",
        name: "Tutor 2",
        avatar: "/assets/avatar-tutor-3.png",
        age: 22,
        yoe: 2,
        gender: "Female",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
      {
        id: "3",
        name: "Tutor 3",
        avatar: "/assets/avatar-tutor-2.png",
        age: 22,
        yoe: 2,
        gender: "Male",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
    ],
  },
  {
    id: "2",
    nameCourse: "Môn học 2",
    descriptionCourse: "Mô tả Môn học 2",
    tutors: [
      {
        id: "1",
        name: "Tutor 1",
        avatar: "/assets/avatar-tutor-2.png",
        age: 22,
        yoe: 2,
        gender: "Male",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
      {
        id: "2",
        name: "Tutor 2",
        avatar: "/assets/avatar-tutor-3.png",
        age: 22,
        yoe: 2,
        gender: "Female",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
      {
        id: "3",
        name: "Tutor 3",
        avatar: "/assets/avatar-tutor-2.png",
        age: 22,
        yoe: 2,
        gender: "Male",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
    ],
  },
  {
    id: "3",
    nameCourse: "Môn học 3",
    descriptionCourse: "Mô tả Môn học 3",
    tutors: [
      {
        id: "1",
        name: "Tutor 1",
        avatar: "/assets/avatar-tutor-2.png",
        age: 22,
        yoe: 2,
        gender: "Male",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
      {
        id: "2",
        name: "Tutor 2",
        avatar: "/assets/avatar-tutor-3.png",
        age: 22,
        yoe: 2,
        gender: "Female",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
      {
        id: "3",
        name: "Tutor 3",
        avatar: "/assets/avatar-tutor-2.png",
        age: 22,
        yoe: 2,
        gender: "Male",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
    ],
  },
]

export const moreFieldCourses = [
  {
    id: "4",
    nameCourse: "Môn học 4",
    descriptionCourse: "Môn học 4",
    tutors: [
      {
        id: "1",
        name: "Tutor 1",
        avatar: "/assets/avatar-tutor-2.png",
        age: 22,
        yoe: 2,
        gender: "Male",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
      {
        id: "2",
        name: "Tutor 2",
        avatar: "/assets/avatar-tutor-3.png",
        age: 22,
        yoe: 2,
        gender: "Female",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
      {
        id: "3",
        name: "Tutor 3",
        avatar: "/assets/avatar-tutor-2.png",
        age: 22,
        yoe: 2,
        gender: "Male",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
    ],
  },
  {
    id: "5",
    nameCourse: "Môn học 5",
    descriptionCourse: "Mô tả Môn học 5",
    tutors: [
      {
        id: "1",
        name: "Tutor 1",
        avatar: "/assets/avatar-tutor-2.png",
        age: 22,
        yoe: 2,
        gender: "Male",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
      {
        id: "2",
        name: "Tutor 2",
        avatar: "/assets/avatar-tutor-3.png",
        age: 22,
        yoe: 2,
        gender: "Female",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
      {
        id: "3",
        name: "Tutor 3",
        avatar: "/assets/avatar-tutor-2.png",
        age: 22,
        yoe: 2,
        gender: "Male",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
    ],
  },
  {
    id: "6",
    nameCourse: "Môn học 6",
    descriptionCourse: "Mô tả Môn học 6",
    tutors: [
      {
        id: "1",
        name: "Tutor 1",
        avatar: "/assets/avatar-tutor-2.png",
        age: 22,
        yoe: 2,
        gender: "Male",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
      {
        id: "2",
        name: "Tutor 2",
        avatar: "/assets/avatar-tutor-3.png",
        age: 22,
        yoe: 2,
        gender: "Female",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
      {
        id: "3",
        name: "Tutor 3",
        avatar: "/assets/avatar-tutor-2.png",
        age: 22,
        yoe: 2,
        gender: "Male",
        city: "City 1",
        description: "Mô tả tutor 1",
        link: "",
      },
    ],
  },
]
